'use client';

import { useEffect, useRef } from 'react';

/**
 * Checks whether an event target originates inside a gesture-managed component
 * (such as react-zoom-pan-pinch TransformWrapper on the office map, or horizontal queue sliders).
 *
 * NOTE ON MULTIPLE SELECTORS:
 * We use an explicit belt-and-suspenders selector list:
 * - `[data-no-swipe-back="true"]`: Our explicit project-level opt-out attribute.
 * - `.react-transform-component`: Standard class generated by react-zoom-pan-pinch container.
 * - `.react-transform-wrapper`: Standard outer wrapper generated by react-zoom-pan-pinch.
 * - `[data-transform-wrapper]`: Defensive attribute backup across library major versions.
 *
 * DO NOT remove any of these selectors during refactors; they prevent the swipe-back hook
 * from intercepting pan/zoom pinches on the office map across different build targets.
 */
export function isSwipeBackExcluded(target: EventTarget | null): boolean {
  if (!target || typeof (target as Element).closest !== 'function') {
    return false;
  }
  const el = target as Element;
  return Boolean(
    el.closest(
      '[data-no-swipe-back="true"], .react-transform-component, .react-transform-wrapper, [data-transform-wrapper]'
    )
  );
}

interface UseSwipeBackOptions {
  onBack: () => void;
  enabled?: boolean;
  edgeThreshold?: number; // Distance in px from left edge to start tracking (default: 40px)
  minSwipeDistance?: number; // Minimum horizontal distance to trigger back (default: 80px)
  maxVerticalDeviation?: number; // Maximum allowed vertical movement before canceling (default: 60px)
}

export function useSwipeBack({
  onBack,
  enabled = true,
  edgeThreshold = 40,
  minSwipeDistance = 80,
  maxVerticalDeviation = 60,
}: UseSwipeBackOptions) {
  const touchStartRef = useRef<{ x: number; y: number; valid: boolean } | null>(null);

  useEffect(() => {
    if (!enabled || typeof window === 'undefined') return;

    const handleTouchStart = (e: TouchEvent) => {
      if (e.touches.length !== 1) {
        touchStartRef.current = null;
        return;
      }

      const touch = e.touches[0];
      const target = e.target;

      // 1. Boundary check: immediately ignore if touch starts inside map or gesture-owned area
      if (isSwipeBackExcluded(target)) {
        touchStartRef.current = { x: touch.clientX, y: touch.clientY, valid: false };
        return;
      }

      // 2. Edge check: must initiate within the left-edge threshold (e.g. < 40px)
      if (touch.clientX <= edgeThreshold) {
        touchStartRef.current = { x: touch.clientX, y: touch.clientY, valid: true };
      } else {
        touchStartRef.current = null;
      }
    };

    const handleTouchEnd = (e: TouchEvent) => {
      const start = touchStartRef.current;
      touchStartRef.current = null;

      if (!start || !start.valid) return;

      const touch = e.changedTouches[0];
      if (!touch) return;

      const deltaX = touch.clientX - start.x;
      const deltaY = Math.abs(touch.clientY - start.y);

      // Verify horizontal dominance and minimum swipe distance
      if (deltaX >= minSwipeDistance && deltaY <= maxVerticalDeviation) {
        onBack();
      }
    };

    window.addEventListener('touchstart', handleTouchStart, { passive: true });
    window.addEventListener('touchend', handleTouchEnd, { passive: true });

    return () => {
      window.removeEventListener('touchstart', handleTouchStart);
      window.removeEventListener('touchend', handleTouchEnd);
    };
  }, [enabled, onBack, edgeThreshold, minSwipeDistance, maxVerticalDeviation]);
}
